### ISSUE TITLE
add link to download pdf report

### ISSUE THREAD

**Issue by jessicamcinchak** [datajustice/report#5]

**Comment by skristyn** [comment]
Will do this tomorrow, the updated version of the report is on my work computer. Hopefully you can show the old draft to the group today - all that's updated is the graphics, i.e. the rocket ship has been changed to a UFO.

**Comment by jessicamcinchak** [comment]
Content edits to the recommendations are bigger than a day after hearing lots of feedback -- but we can still mock up this feature with a sample pdf in the meantime.

One option is to: create a new folder in the repo called 'downloads', upload a pdf file, then link an icon/image/text/whatever using the html5 download attr like this: `<a href="http://link/to/file" download="FileName">Download it!</a>`. Alternatively, we can use javascript too.

https://stackoverflow.com/questions/6794255/html-download-a-pdf-file-instead-of-opening-them-in-browser-when-clicked

**Comment by skristyn** [comment]
Do we not want it to open in the browser first? I kind of like previewing PDF files in the browser and then saving them from there. Perhaps it's annoying to other people, though.

**Comment by jessicamcinchak** [comment]
Agreed - let's set to preview
